### ISSUE TITLE
Grafisk avvik: Søkeknappen er ikke alignet riktig

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aap-kalkulator-frontend#2]
![image](https://user-images.githubusercontent.com/91880567/181741558-3aff4b0f-e7fa-43b1-b486-95bb08dc5fee.png)

**Comment by VHollund** [comment]
Fixed at [https://github.com/navikt/aap-kalkulator-frontend/commit/566ee3c4ff76111dbc3bda0cf8630f750b251188](https://github.com/navikt/aap-kalkulator-frontend/commit/566ee3c4ff76111dbc3bda0cf8630f750b251188)
