### ISSUE TITLE
uu: gi mulighet til å hoppe direkte til hovedinnholdet

### ISSUE THREAD

**Issue by amratk** [navikt/aap-kalkulator-frontend#3]
gjelder 2.4.1 hoppe over blokker:
kan fikses ved å legge til main element i html, gjerne med en skiplink/hopp over lenke til main elementet/hovedinnholdet. F.eks. slik de har gjort det på https://www.nav.no/.

**Comment by VHollund** [comment]
Fikset i 628842dc23410b9b0503280b312cf5b04bc12a78
