### ISSUE TITLE
uu: 4.1.1 Parsing

### ISSUE THREAD

**Issue by amratk** [navikt/aap-kalkulator-frontend#5]
<img width="1598" alt="Skjermbilde 2022-07-29 kl  14 49 06" src="https://user-images.githubusercontent.com/110233513/181763935-ffa47fd9-6f9f-49f8-a9e7-edc8ff5e6ac6.png">

**Comment by VHollund** [comment]
Fixed as of f0c2531c99b192a2d744882227d683ab49d1a1ec
