### ISSUE TITLE
4.1.2 navn, rolle, verdi: "timer per uke" er ikke koblet til input-feltet. 

### ISSUE THREAD

**Issue by amratk** [navikt/aap-kalkulator-frontend#8]
<img width="466" alt="Skjermbilde 2022-07-29 kl  15 24 48" src="https://user-images.githubusercontent.com/110233513/181769960-a7971ca7-24c7-46fc-b4bd-e5a345ff3ffc.png">

**Comment by VHollund** [comment]
Fixed at 7068699dbff663b83389b5f82474508c7599c312
