### ISSUE TITLE
Feilmelding er ikke koblet til feltet

### ISSUE THREAD

**Issue by amratk** [navikt/aap-kalkulator-frontend#9]
<img width="480" alt="Skjermbilde 2022-07-29 kl  15 29 43" src="https://user-images.githubusercontent.com/110233513/181770731-e2d3391e-c3c2-4424-b401-4ee0d7e1ad16.png">

Feilmeldingen er ikke koblet til feltet med feil. bruk gjerne aria-describedby her.

**Comment by vildeopp** [comment]
fikset ved d0639079b4a58052810e720be9e7d4820fa1c451
